// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: aserto/api/v1/change.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChangeType int32

const (
	ChangeType_CHANGE_TYPE_UNKNOWN ChangeType = 0
	ChangeType_CHANGE_TYPE_CREATED ChangeType = 1
	ChangeType_CHANGE_TYPE_UPDATED ChangeType = 2
	ChangeType_CHANGE_TYPE_DELETED ChangeType = 3
)

// Enum value maps for ChangeType.
var (
	ChangeType_name = map[int32]string{
		0: "CHANGE_TYPE_UNKNOWN",
		1: "CHANGE_TYPE_CREATED",
		2: "CHANGE_TYPE_UPDATED",
		3: "CHANGE_TYPE_DELETED",
	}
	ChangeType_value = map[string]int32{
		"CHANGE_TYPE_UNKNOWN": 0,
		"CHANGE_TYPE_CREATED": 1,
		"CHANGE_TYPE_UPDATED": 2,
		"CHANGE_TYPE_DELETED": 3,
	}
)

func (x ChangeType) Enum() *ChangeType {
	p := new(ChangeType)
	*p = x
	return p
}

func (x ChangeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChangeType) Descriptor() protoreflect.EnumDescriptor {
	return file_aserto_api_v1_change_proto_enumTypes[0].Descriptor()
}

func (ChangeType) Type() protoreflect.EnumType {
	return &file_aserto_api_v1_change_proto_enumTypes[0]
}

func (x ChangeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChangeType.Descriptor instead.
func (ChangeType) EnumDescriptor() ([]byte, []int) {
	return file_aserto_api_v1_change_proto_rawDescGZIP(), []int{0}
}

var File_aserto_api_v1_change_proto protoreflect.FileDescriptor

const file_aserto_api_v1_change_proto_rawDesc = "" +
	"\n" +
	"\x1aaserto/api/v1/change.proto\x12\raserto.api.v1*p\n" +
	"\n" +
	"ChangeType\x12\x17\n" +
	"\x13CHANGE_TYPE_UNKNOWN\x10\x00\x12\x17\n" +
	"\x13CHANGE_TYPE_CREATED\x10\x01\x12\x17\n" +
	"\x13CHANGE_TYPE_UPDATED\x10\x02\x12\x17\n" +
	"\x13CHANGE_TYPE_DELETED\x10\x03BAZ/github.com/aserto-dev/go-grpc/aserto/api/v1;api\xaa\x02\rAserto.API.V1b\x06proto3"

var (
	file_aserto_api_v1_change_proto_rawDescOnce sync.Once
	file_aserto_api_v1_change_proto_rawDescData []byte
)

func file_aserto_api_v1_change_proto_rawDescGZIP() []byte {
	file_aserto_api_v1_change_proto_rawDescOnce.Do(func() {
		file_aserto_api_v1_change_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aserto_api_v1_change_proto_rawDesc), len(file_aserto_api_v1_change_proto_rawDesc)))
	})
	return file_aserto_api_v1_change_proto_rawDescData
}

var file_aserto_api_v1_change_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_aserto_api_v1_change_proto_goTypes = []any{
	(ChangeType)(0), // 0: aserto.api.v1.ChangeType
}
var file_aserto_api_v1_change_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_aserto_api_v1_change_proto_init() }
func file_aserto_api_v1_change_proto_init() {
	if File_aserto_api_v1_change_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aserto_api_v1_change_proto_rawDesc), len(file_aserto_api_v1_change_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aserto_api_v1_change_proto_goTypes,
		DependencyIndexes: file_aserto_api_v1_change_proto_depIdxs,
		EnumInfos:         file_aserto_api_v1_change_proto_enumTypes,
	}.Build()
	File_aserto_api_v1_change_proto = out.File
	file_aserto_api_v1_change_proto_goTypes = nil
	file_aserto_api_v1_change_proto_depIdxs = nil
}
