// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: aserto/api/v1/registry.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegistryRepo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Org           string                 `protobuf:"bytes,2,opt,name=org,proto3" json:"org,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryRepo) Reset() {
	*x = RegistryRepo{}
	mi := &file_aserto_api_v1_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryRepo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryRepo) ProtoMessage() {}

func (x *RegistryRepo) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_api_v1_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryRepo.ProtoReflect.Descriptor instead.
func (*RegistryRepo) Descriptor() ([]byte, []int) {
	return file_aserto_api_v1_registry_proto_rawDescGZIP(), []int{0}
}

func (x *RegistryRepo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegistryRepo) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

type RegistryRepoTag struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Name          string                    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Digest        string                    `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	Size          int64                     `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	CreatedAt     *timestamppb.Timestamp    `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Annotations   []*RegistryRepoAnnotation `protobuf:"bytes,5,rep,name=annotations,proto3" json:"annotations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryRepoTag) Reset() {
	*x = RegistryRepoTag{}
	mi := &file_aserto_api_v1_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryRepoTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryRepoTag) ProtoMessage() {}

func (x *RegistryRepoTag) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_api_v1_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryRepoTag.ProtoReflect.Descriptor instead.
func (*RegistryRepoTag) Descriptor() ([]byte, []int) {
	return file_aserto_api_v1_registry_proto_rawDescGZIP(), []int{1}
}

func (x *RegistryRepoTag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegistryRepoTag) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *RegistryRepoTag) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *RegistryRepoTag) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *RegistryRepoTag) GetAnnotations() []*RegistryRepoAnnotation {
	if x != nil {
		return x.Annotations
	}
	return nil
}

type RegistryRepoAnnotation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryRepoAnnotation) Reset() {
	*x = RegistryRepoAnnotation{}
	mi := &file_aserto_api_v1_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryRepoAnnotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryRepoAnnotation) ProtoMessage() {}

func (x *RegistryRepoAnnotation) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_api_v1_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryRepoAnnotation.ProtoReflect.Descriptor instead.
func (*RegistryRepoAnnotation) Descriptor() ([]byte, []int) {
	return file_aserto_api_v1_registry_proto_rawDescGZIP(), []int{2}
}

func (x *RegistryRepoAnnotation) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RegistryRepoAnnotation) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type RegistryRepoDigest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Digest        string                 `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	Tags          []string               `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryRepoDigest) Reset() {
	*x = RegistryRepoDigest{}
	mi := &file_aserto_api_v1_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryRepoDigest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryRepoDigest) ProtoMessage() {}

func (x *RegistryRepoDigest) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_api_v1_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryRepoDigest.ProtoReflect.Descriptor instead.
func (*RegistryRepoDigest) Descriptor() ([]byte, []int) {
	return file_aserto_api_v1_registry_proto_rawDescGZIP(), []int{3}
}

func (x *RegistryRepoDigest) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *RegistryRepoDigest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *RegistryRepoDigest) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_aserto_api_v1_registry_proto protoreflect.FileDescriptor

const file_aserto_api_v1_registry_proto_rawDesc = "" +
	"\n" +
	"\x1caserto/api/v1/registry.proto\x12\raserto.api.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"4\n" +
	"\fRegistryRepo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03org\x18\x02 \x01(\tR\x03org\"\xd5\x01\n" +
	"\x0fRegistryRepoTag\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\tR\x06digest\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12G\n" +
	"\vannotations\x18\x05 \x03(\v2%.aserto.api.v1.RegistryRepoAnnotationR\vannotations\"@\n" +
	"\x16RegistryRepoAnnotation\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"{\n" +
	"\x12RegistryRepoDigest\x12\x16\n" +
	"\x06digest\x18\x01 \x01(\tR\x06digest\x12\x12\n" +
	"\x04tags\x18\x02 \x03(\tR\x04tags\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtBAZ/github.com/aserto-dev/go-grpc/aserto/api/v1;api\xaa\x02\rAserto.API.V1b\x06proto3"

var (
	file_aserto_api_v1_registry_proto_rawDescOnce sync.Once
	file_aserto_api_v1_registry_proto_rawDescData []byte
)

func file_aserto_api_v1_registry_proto_rawDescGZIP() []byte {
	file_aserto_api_v1_registry_proto_rawDescOnce.Do(func() {
		file_aserto_api_v1_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aserto_api_v1_registry_proto_rawDesc), len(file_aserto_api_v1_registry_proto_rawDesc)))
	})
	return file_aserto_api_v1_registry_proto_rawDescData
}

var file_aserto_api_v1_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_aserto_api_v1_registry_proto_goTypes = []any{
	(*RegistryRepo)(nil),           // 0: aserto.api.v1.RegistryRepo
	(*RegistryRepoTag)(nil),        // 1: aserto.api.v1.RegistryRepoTag
	(*RegistryRepoAnnotation)(nil), // 2: aserto.api.v1.RegistryRepoAnnotation
	(*RegistryRepoDigest)(nil),     // 3: aserto.api.v1.RegistryRepoDigest
	(*timestamppb.Timestamp)(nil),  // 4: google.protobuf.Timestamp
}
var file_aserto_api_v1_registry_proto_depIdxs = []int32{
	4, // 0: aserto.api.v1.RegistryRepoTag.created_at:type_name -> google.protobuf.Timestamp
	2, // 1: aserto.api.v1.RegistryRepoTag.annotations:type_name -> aserto.api.v1.RegistryRepoAnnotation
	4, // 2: aserto.api.v1.RegistryRepoDigest.created_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_aserto_api_v1_registry_proto_init() }
func file_aserto_api_v1_registry_proto_init() {
	if File_aserto_api_v1_registry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aserto_api_v1_registry_proto_rawDesc), len(file_aserto_api_v1_registry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aserto_api_v1_registry_proto_goTypes,
		DependencyIndexes: file_aserto_api_v1_registry_proto_depIdxs,
		MessageInfos:      file_aserto_api_v1_registry_proto_msgTypes,
	}.Build()
	File_aserto_api_v1_registry_proto = out.File
	file_aserto_api_v1_registry_proto_goTypes = nil
	file_aserto_api_v1_registry_proto_depIdxs = nil
}
