// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: aserto/api/v1/user.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IdentityKind int32

const (
	IdentityKind_IDENTITY_KIND_UNKNOWN  IdentityKind = 0 // undefined state
	IdentityKind_IDENTITY_KIND_PID      IdentityKind = 1 // provider unique identifier
	IdentityKind_IDENTITY_KIND_EMAIL    IdentityKind = 2 // email address
	IdentityKind_IDENTITY_KIND_USERNAME IdentityKind = 3 // username
	IdentityKind_IDENTITY_KIND_DN       IdentityKind = 4 // distinguished name format RFC1779
	IdentityKind_IDENTITY_KIND_PHONE    IdentityKind = 5 // phonenumber using the format described in RFC3966, +1-201-555-0111 (without the tel: prefix)
	IdentityKind_IDENTITY_KIND_EMPID    IdentityKind = 6 // employee identifier
)

// Enum value maps for IdentityKind.
var (
	IdentityKind_name = map[int32]string{
		0: "IDENTITY_KIND_UNKNOWN",
		1: "IDENTITY_KIND_PID",
		2: "IDENTITY_KIND_EMAIL",
		3: "IDENTITY_KIND_USERNAME",
		4: "IDENTITY_KIND_DN",
		5: "IDENTITY_KIND_PHONE",
		6: "IDENTITY_KIND_EMPID",
	}
	IdentityKind_value = map[string]int32{
		"IDENTITY_KIND_UNKNOWN":  0,
		"IDENTITY_KIND_PID":      1,
		"IDENTITY_KIND_EMAIL":    2,
		"IDENTITY_KIND_USERNAME": 3,
		"IDENTITY_KIND_DN":       4,
		"IDENTITY_KIND_PHONE":    5,
		"IDENTITY_KIND_EMPID":    6,
	}
)

func (x IdentityKind) Enum() *IdentityKind {
	p := new(IdentityKind)
	*p = x
	return p
}

func (x IdentityKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IdentityKind) Descriptor() protoreflect.EnumDescriptor {
	return file_aserto_api_v1_user_proto_enumTypes[0].Descriptor()
}

func (IdentityKind) Type() protoreflect.EnumType {
	return &file_aserto_api_v1_user_proto_enumTypes[0]
}

func (x IdentityKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IdentityKind.Descriptor instead.
func (IdentityKind) EnumDescriptor() ([]byte, []int) {
	return file_aserto_api_v1_user_proto_rawDescGZIP(), []int{0}
}

type AttrKind int32

const (
	AttrKind_ATTR_KIND_UNKNOWN         AttrKind = 0  // undefined state
	AttrKind_ATTR_KIND_TITLE           AttrKind = 1  // title attribute
	AttrKind_ATTR_KIND_DEPARTMENT      AttrKind = 2  // department attribute
	AttrKind_ATTR_KIND_DIVSION         AttrKind = 3  // division attribute
	AttrKind_ATTR_KIND_COMPANY         AttrKind = 4  // company attribute
	AttrKind_ATTR_KIND_EMPLOYEE_ID     AttrKind = 5  // employee id attribute
	AttrKind_ATTR_KIND_EMPLOYEE_TYPE   AttrKind = 6  // employee type (fulltime, contractor, etc.)
	AttrKind_ATTR_KIND_EMPLOYEE_NUMBER AttrKind = 7  // employee number
	AttrKind_ATTR_KIND_MANAGER         AttrKind = 8  // manager (identity value)
	AttrKind_ATTR_KIND_FIRST_NAME      AttrKind = 9  // user first name attribute
	AttrKind_ATTR_KIND_INITIALS        AttrKind = 10 // user initials attribute
	AttrKind_ATTR_KIND_LAST_NAME       AttrKind = 11 // user last name attribute
	AttrKind_ATTR_KIND_COMMON_NAME     AttrKind = 12 // user common name attribute
)

// Enum value maps for AttrKind.
var (
	AttrKind_name = map[int32]string{
		0:  "ATTR_KIND_UNKNOWN",
		1:  "ATTR_KIND_TITLE",
		2:  "ATTR_KIND_DEPARTMENT",
		3:  "ATTR_KIND_DIVSION",
		4:  "ATTR_KIND_COMPANY",
		5:  "ATTR_KIND_EMPLOYEE_ID",
		6:  "ATTR_KIND_EMPLOYEE_TYPE",
		7:  "ATTR_KIND_EMPLOYEE_NUMBER",
		8:  "ATTR_KIND_MANAGER",
		9:  "ATTR_KIND_FIRST_NAME",
		10: "ATTR_KIND_INITIALS",
		11: "ATTR_KIND_LAST_NAME",
		12: "ATTR_KIND_COMMON_NAME",
	}
	AttrKind_value = map[string]int32{
		"ATTR_KIND_UNKNOWN":         0,
		"ATTR_KIND_TITLE":           1,
		"ATTR_KIND_DEPARTMENT":      2,
		"ATTR_KIND_DIVSION":         3,
		"ATTR_KIND_COMPANY":         4,
		"ATTR_KIND_EMPLOYEE_ID":     5,
		"ATTR_KIND_EMPLOYEE_TYPE":   6,
		"ATTR_KIND_EMPLOYEE_NUMBER": 7,
		"ATTR_KIND_MANAGER":         8,
		"ATTR_KIND_FIRST_NAME":      9,
		"ATTR_KIND_INITIALS":        10,
		"ATTR_KIND_LAST_NAME":       11,
		"ATTR_KIND_COMMON_NAME":     12,
	}
)

func (x AttrKind) Enum() *AttrKind {
	p := new(AttrKind)
	*p = x
	return p
}

func (x AttrKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AttrKind) Descriptor() protoreflect.EnumDescriptor {
	return file_aserto_api_v1_user_proto_enumTypes[1].Descriptor()
}

func (AttrKind) Type() protoreflect.EnumType {
	return &file_aserto_api_v1_user_proto_enumTypes[1]
}

func (x AttrKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AttrKind.Descriptor instead.
func (AttrKind) EnumDescriptor() ([]byte, []int) {
	return file_aserto_api_v1_user_proto_rawDescGZIP(), []int{1}
}

type User struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Id            string                     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                                               // IDP PID
	Enabled       *bool                      `protobuf:"varint,2,opt,name=enabled,proto3,oneof" json:"enabled,omitempty"`                                                                              // enabled (false disables identity to access anything)
	DisplayName   string                     `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`                                                          // display name of user
	Email         string                     `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`                                                                                         // main email address of user
	Picture       string                     `protobuf:"bytes,5,opt,name=picture,proto3" json:"picture,omitempty"`                                                                                     // URL to user's picture
	Identities    map[string]*IdentitySource `protobuf:"bytes,6,rep,name=identities,proto3" json:"identities,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`     // identity source collection of user
	Attributes    *AttrSet                   `protobuf:"bytes,7,opt,name=attributes,proto3" json:"attributes,omitempty"`                                                                               // globally scoped user attributes (properties, roles and permissions)
	Applications  map[string]*AttrSet        `protobuf:"bytes,8,rep,name=applications,proto3" json:"applications,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // application scoped attributes (properties, roles and permissions)
	Metadata      *Metadata                  `protobuf:"bytes,9,opt,name=metadata,proto3" json:"metadata,omitempty"`                                                                                   // generic metadata results block
	Deleted       bool                       `protobuf:"varint,10,opt,name=deleted,proto3" json:"deleted,omitempty"`                                                                                   // deleted markation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_aserto_api_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_api_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_aserto_api_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

func (x *User) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

func (x *User) GetIdentities() map[string]*IdentitySource {
	if x != nil {
		return x.Identities
	}
	return nil
}

func (x *User) GetAttributes() *AttrSet {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *User) GetApplications() map[string]*AttrSet {
	if x != nil {
		return x.Applications
	}
	return nil
}

func (x *User) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *User) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type UserExt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                                               // IDP PID
	Attributes    *AttrSet               `protobuf:"bytes,7,opt,name=attributes,proto3" json:"attributes,omitempty"`                                                                               // globally scoped user attributes (properties, roles and permissions)
	Applications  map[string]*AttrSet    `protobuf:"bytes,8,rep,name=applications,proto3" json:"applications,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // application scoped attributes (properties, roles and permissions)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserExt) Reset() {
	*x = UserExt{}
	mi := &file_aserto_api_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserExt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserExt) ProtoMessage() {}

func (x *UserExt) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_api_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserExt.ProtoReflect.Descriptor instead.
func (*UserExt) Descriptor() ([]byte, []int) {
	return file_aserto_api_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserExt) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserExt) GetAttributes() *AttrSet {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *UserExt) GetApplications() map[string]*AttrSet {
	if x != nil {
		return x.Applications
	}
	return nil
}

type DeleteUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // IDP PID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUser) Reset() {
	*x = DeleteUser{}
	mi := &file_aserto_api_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUser) ProtoMessage() {}

func (x *DeleteUser) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_api_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUser.ProtoReflect.Descriptor instead.
func (*DeleteUser) Descriptor() ([]byte, []int) {
	return file_aserto_api_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteUser) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteConnection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId  string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"` // IDP connection ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConnection) Reset() {
	*x = DeleteConnection{}
	mi := &file_aserto_api_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConnection) ProtoMessage() {}

func (x *DeleteConnection) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_api_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConnection.ProtoReflect.Descriptor instead.
func (*DeleteConnection) Descriptor() ([]byte, []int) {
	return file_aserto_api_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteConnection) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

type AttrSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Properties    *structpb.Struct       `protobuf:"bytes,1,opt,name=properties,proto3" json:"properties,omitempty"`   // property map
	Roles         []string               `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`             // roles of which the user is a member of
	Permissions   []string               `protobuf:"bytes,4,rep,name=permissions,proto3" json:"permissions,omitempty"` // permissions owned by user
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttrSet) Reset() {
	*x = AttrSet{}
	mi := &file_aserto_api_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttrSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttrSet) ProtoMessage() {}

func (x *AttrSet) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_api_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttrSet.ProtoReflect.Descriptor instead.
func (*AttrSet) Descriptor() ([]byte, []int) {
	return file_aserto_api_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *AttrSet) GetProperties() *structpb.Struct {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *AttrSet) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *AttrSet) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

// ApplExt, message definition only used for storage serialization
type ApplExt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Applications  map[string]*AttrSet    `protobuf:"bytes,1,rep,name=applications,proto3" json:"applications,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplExt) Reset() {
	*x = ApplExt{}
	mi := &file_aserto_api_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplExt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplExt) ProtoMessage() {}

func (x *ApplExt) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_api_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplExt.ProtoReflect.Descriptor instead.
func (*ApplExt) Descriptor() ([]byte, []int) {
	return file_aserto_api_v1_user_proto_rawDescGZIP(), []int{5}
}

func (x *ApplExt) GetApplications() map[string]*AttrSet {
	if x != nil {
		return x.Applications
	}
	return nil
}

type IdentitySource struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Kind            IdentityKind           `protobuf:"varint,1,opt,name=kind,proto3,enum=aserto.api.v1.IdentityKind" json:"kind,omitempty"`                    // identity kind [email|username|uid|pid|dn|phone]
	Provider        string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`                                             // identity provider
	Verified        bool                   `protobuf:"varint,3,opt,name=verified,proto3" json:"verified,omitempty"`                                            // identity has been verified (false when not explicitly specified)
	ConnectionId    *string                `protobuf:"bytes,4,opt,name=connection_id,json=connectionId,proto3,oneof" json:"connection_id,omitempty"`           // IDP connection id which owns the object instance
	CaseInsensitive *bool                  `protobuf:"varint,5,opt,name=case_insensitive,json=caseInsensitive,proto3,oneof" json:"case_insensitive,omitempty"` // compare value property case-insenstive, default value comparison is case-sensitive
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IdentitySource) Reset() {
	*x = IdentitySource{}
	mi := &file_aserto_api_v1_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentitySource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentitySource) ProtoMessage() {}

func (x *IdentitySource) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_api_v1_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentitySource.ProtoReflect.Descriptor instead.
func (*IdentitySource) Descriptor() ([]byte, []int) {
	return file_aserto_api_v1_user_proto_rawDescGZIP(), []int{6}
}

func (x *IdentitySource) GetKind() IdentityKind {
	if x != nil {
		return x.Kind
	}
	return IdentityKind_IDENTITY_KIND_UNKNOWN
}

func (x *IdentitySource) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *IdentitySource) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *IdentitySource) GetConnectionId() string {
	if x != nil && x.ConnectionId != nil {
		return *x.ConnectionId
	}
	return ""
}

func (x *IdentitySource) GetCaseInsensitive() bool {
	if x != nil && x.CaseInsensitive != nil {
		return *x.CaseInsensitive
	}
	return false
}

type UserProcessStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Received      int32                  `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`
	Created       int32                  `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	Updated       int32                  `protobuf:"varint,3,opt,name=updated,proto3" json:"updated,omitempty"`
	Deleted       int32                  `protobuf:"varint,4,opt,name=deleted,proto3" json:"deleted,omitempty"`
	Errors        int32                  `protobuf:"varint,5,opt,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProcessStats) Reset() {
	*x = UserProcessStats{}
	mi := &file_aserto_api_v1_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProcessStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProcessStats) ProtoMessage() {}

func (x *UserProcessStats) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_api_v1_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProcessStats.ProtoReflect.Descriptor instead.
func (*UserProcessStats) Descriptor() ([]byte, []int) {
	return file_aserto_api_v1_user_proto_rawDescGZIP(), []int{7}
}

func (x *UserProcessStats) GetReceived() int32 {
	if x != nil {
		return x.Received
	}
	return 0
}

func (x *UserProcessStats) GetCreated() int32 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *UserProcessStats) GetUpdated() int32 {
	if x != nil {
		return x.Updated
	}
	return 0
}

func (x *UserProcessStats) GetDeleted() int32 {
	if x != nil {
		return x.Deleted
	}
	return 0
}

func (x *UserProcessStats) GetErrors() int32 {
	if x != nil {
		return x.Errors
	}
	return 0
}

var File_aserto_api_v1_user_proto protoreflect.FileDescriptor

const file_aserto_api_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x18aserto/api/v1/user.proto\x12\raserto.api.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1caserto/api/v1/metadata.proto\"\xe2\x04\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\aenabled\x18\x02 \x01(\bH\x00R\aenabled\x88\x01\x01\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x18\n" +
	"\apicture\x18\x05 \x01(\tR\apicture\x12C\n" +
	"\n" +
	"identities\x18\x06 \x03(\v2#.aserto.api.v1.User.IdentitiesEntryR\n" +
	"identities\x126\n" +
	"\n" +
	"attributes\x18\a \x01(\v2\x16.aserto.api.v1.AttrSetR\n" +
	"attributes\x12I\n" +
	"\fapplications\x18\b \x03(\v2%.aserto.api.v1.User.ApplicationsEntryR\fapplications\x123\n" +
	"\bmetadata\x18\t \x01(\v2\x17.aserto.api.v1.MetadataR\bmetadata\x12\x18\n" +
	"\adeleted\x18\n" +
	" \x01(\bR\adeleted\x1a\\\n" +
	"\x0fIdentitiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x123\n" +
	"\x05value\x18\x02 \x01(\v2\x1d.aserto.api.v1.IdentitySourceR\x05value:\x028\x01\x1aW\n" +
	"\x11ApplicationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.aserto.api.v1.AttrSetR\x05value:\x028\x01B\n" +
	"\n" +
	"\b_enabled\"\xf8\x01\n" +
	"\aUserExt\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x126\n" +
	"\n" +
	"attributes\x18\a \x01(\v2\x16.aserto.api.v1.AttrSetR\n" +
	"attributes\x12L\n" +
	"\fapplications\x18\b \x03(\v2(.aserto.api.v1.UserExt.ApplicationsEntryR\fapplications\x1aW\n" +
	"\x11ApplicationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.aserto.api.v1.AttrSetR\x05value:\x028\x01\"\x1c\n" +
	"\n" +
	"DeleteUser\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"7\n" +
	"\x10DeleteConnection\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\"\x80\x01\n" +
	"\aAttrSet\x127\n" +
	"\n" +
	"properties\x18\x01 \x01(\v2\x17.google.protobuf.StructR\n" +
	"properties\x12\x14\n" +
	"\x05roles\x18\x02 \x03(\tR\x05roles\x12 \n" +
	"\vpermissions\x18\x04 \x03(\tR\vpermissionsJ\x04\b\x03\x10\x04\"\xb0\x01\n" +
	"\aApplExt\x12L\n" +
	"\fapplications\x18\x01 \x03(\v2(.aserto.api.v1.ApplExt.ApplicationsEntryR\fapplications\x1aW\n" +
	"\x11ApplicationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.aserto.api.v1.AttrSetR\x05value:\x028\x01\"\xfa\x01\n" +
	"\x0eIdentitySource\x12/\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1b.aserto.api.v1.IdentityKindR\x04kind\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x1a\n" +
	"\bverified\x18\x03 \x01(\bR\bverified\x12(\n" +
	"\rconnection_id\x18\x04 \x01(\tH\x00R\fconnectionId\x88\x01\x01\x12.\n" +
	"\x10case_insensitive\x18\x05 \x01(\bH\x01R\x0fcaseInsensitive\x88\x01\x01B\x10\n" +
	"\x0e_connection_idB\x13\n" +
	"\x11_case_insensitive\"\x94\x01\n" +
	"\x10UserProcessStats\x12\x1a\n" +
	"\breceived\x18\x01 \x01(\x05R\breceived\x12\x18\n" +
	"\acreated\x18\x02 \x01(\x05R\acreated\x12\x18\n" +
	"\aupdated\x18\x03 \x01(\x05R\aupdated\x12\x18\n" +
	"\adeleted\x18\x04 \x01(\x05R\adeleted\x12\x16\n" +
	"\x06errors\x18\x05 \x01(\x05R\x06errors*\xbd\x01\n" +
	"\fIdentityKind\x12\x19\n" +
	"\x15IDENTITY_KIND_UNKNOWN\x10\x00\x12\x15\n" +
	"\x11IDENTITY_KIND_PID\x10\x01\x12\x17\n" +
	"\x13IDENTITY_KIND_EMAIL\x10\x02\x12\x1a\n" +
	"\x16IDENTITY_KIND_USERNAME\x10\x03\x12\x14\n" +
	"\x10IDENTITY_KIND_DN\x10\x04\x12\x17\n" +
	"\x13IDENTITY_KIND_PHONE\x10\x05\x12\x17\n" +
	"\x13IDENTITY_KIND_EMPID\x10\x06*\xd2\x02\n" +
	"\bAttrKind\x12\x15\n" +
	"\x11ATTR_KIND_UNKNOWN\x10\x00\x12\x13\n" +
	"\x0fATTR_KIND_TITLE\x10\x01\x12\x18\n" +
	"\x14ATTR_KIND_DEPARTMENT\x10\x02\x12\x15\n" +
	"\x11ATTR_KIND_DIVSION\x10\x03\x12\x15\n" +
	"\x11ATTR_KIND_COMPANY\x10\x04\x12\x19\n" +
	"\x15ATTR_KIND_EMPLOYEE_ID\x10\x05\x12\x1b\n" +
	"\x17ATTR_KIND_EMPLOYEE_TYPE\x10\x06\x12\x1d\n" +
	"\x19ATTR_KIND_EMPLOYEE_NUMBER\x10\a\x12\x15\n" +
	"\x11ATTR_KIND_MANAGER\x10\b\x12\x18\n" +
	"\x14ATTR_KIND_FIRST_NAME\x10\t\x12\x16\n" +
	"\x12ATTR_KIND_INITIALS\x10\n" +
	"\x12\x17\n" +
	"\x13ATTR_KIND_LAST_NAME\x10\v\x12\x19\n" +
	"\x15ATTR_KIND_COMMON_NAME\x10\fBAZ/github.com/aserto-dev/go-grpc/aserto/api/v1;api\xaa\x02\rAserto.API.V1b\x06proto3"

var (
	file_aserto_api_v1_user_proto_rawDescOnce sync.Once
	file_aserto_api_v1_user_proto_rawDescData []byte
)

func file_aserto_api_v1_user_proto_rawDescGZIP() []byte {
	file_aserto_api_v1_user_proto_rawDescOnce.Do(func() {
		file_aserto_api_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aserto_api_v1_user_proto_rawDesc), len(file_aserto_api_v1_user_proto_rawDesc)))
	})
	return file_aserto_api_v1_user_proto_rawDescData
}

var file_aserto_api_v1_user_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_aserto_api_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_aserto_api_v1_user_proto_goTypes = []any{
	(IdentityKind)(0),        // 0: aserto.api.v1.IdentityKind
	(AttrKind)(0),            // 1: aserto.api.v1.AttrKind
	(*User)(nil),             // 2: aserto.api.v1.User
	(*UserExt)(nil),          // 3: aserto.api.v1.UserExt
	(*DeleteUser)(nil),       // 4: aserto.api.v1.DeleteUser
	(*DeleteConnection)(nil), // 5: aserto.api.v1.DeleteConnection
	(*AttrSet)(nil),          // 6: aserto.api.v1.AttrSet
	(*ApplExt)(nil),          // 7: aserto.api.v1.ApplExt
	(*IdentitySource)(nil),   // 8: aserto.api.v1.IdentitySource
	(*UserProcessStats)(nil), // 9: aserto.api.v1.UserProcessStats
	nil,                      // 10: aserto.api.v1.User.IdentitiesEntry
	nil,                      // 11: aserto.api.v1.User.ApplicationsEntry
	nil,                      // 12: aserto.api.v1.UserExt.ApplicationsEntry
	nil,                      // 13: aserto.api.v1.ApplExt.ApplicationsEntry
	(*Metadata)(nil),         // 14: aserto.api.v1.Metadata
	(*structpb.Struct)(nil),  // 15: google.protobuf.Struct
}
var file_aserto_api_v1_user_proto_depIdxs = []int32{
	10, // 0: aserto.api.v1.User.identities:type_name -> aserto.api.v1.User.IdentitiesEntry
	6,  // 1: aserto.api.v1.User.attributes:type_name -> aserto.api.v1.AttrSet
	11, // 2: aserto.api.v1.User.applications:type_name -> aserto.api.v1.User.ApplicationsEntry
	14, // 3: aserto.api.v1.User.metadata:type_name -> aserto.api.v1.Metadata
	6,  // 4: aserto.api.v1.UserExt.attributes:type_name -> aserto.api.v1.AttrSet
	12, // 5: aserto.api.v1.UserExt.applications:type_name -> aserto.api.v1.UserExt.ApplicationsEntry
	15, // 6: aserto.api.v1.AttrSet.properties:type_name -> google.protobuf.Struct
	13, // 7: aserto.api.v1.ApplExt.applications:type_name -> aserto.api.v1.ApplExt.ApplicationsEntry
	0,  // 8: aserto.api.v1.IdentitySource.kind:type_name -> aserto.api.v1.IdentityKind
	8,  // 9: aserto.api.v1.User.IdentitiesEntry.value:type_name -> aserto.api.v1.IdentitySource
	6,  // 10: aserto.api.v1.User.ApplicationsEntry.value:type_name -> aserto.api.v1.AttrSet
	6,  // 11: aserto.api.v1.UserExt.ApplicationsEntry.value:type_name -> aserto.api.v1.AttrSet
	6,  // 12: aserto.api.v1.ApplExt.ApplicationsEntry.value:type_name -> aserto.api.v1.AttrSet
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_aserto_api_v1_user_proto_init() }
func file_aserto_api_v1_user_proto_init() {
	if File_aserto_api_v1_user_proto != nil {
		return
	}
	file_aserto_api_v1_metadata_proto_init()
	file_aserto_api_v1_user_proto_msgTypes[0].OneofWrappers = []any{}
	file_aserto_api_v1_user_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aserto_api_v1_user_proto_rawDesc), len(file_aserto_api_v1_user_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aserto_api_v1_user_proto_goTypes,
		DependencyIndexes: file_aserto_api_v1_user_proto_depIdxs,
		EnumInfos:         file_aserto_api_v1_user_proto_enumTypes,
		MessageInfos:      file_aserto_api_v1_user_proto_msgTypes,
	}.Build()
	File_aserto_api_v1_user_proto = out.File
	file_aserto_api_v1_user_proto_goTypes = nil
	file_aserto_api_v1_user_proto_depIdxs = nil
}
