// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: aserto/options/v1/ids.proto

package options

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IDType int32

const (
	IDType_ID_TYPE_UNKNOWN        IDType = 0
	IDType_ID_TYPE_ACCOUNT        IDType = 1
	IDType_ID_TYPE_TENANT         IDType = 2
	IDType_ID_TYPE_ERROR          IDType = 3
	IDType_ID_TYPE_POLICY         IDType = 4
	IDType_ID_TYPE_REQUEST        IDType = 5
	IDType_ID_TYPE_PROVIDER       IDType = 6
	IDType_ID_TYPE_CONNECTION     IDType = 7
	IDType_ID_TYPE_INVITE         IDType = 8
	IDType_ID_TYPE_POLICY_BUILDER IDType = 9
	IDType_ID_TYPE_POLICY_REPO    IDType = 10
)

// Enum value maps for IDType.
var (
	IDType_name = map[int32]string{
		0:  "ID_TYPE_UNKNOWN",
		1:  "ID_TYPE_ACCOUNT",
		2:  "ID_TYPE_TENANT",
		3:  "ID_TYPE_ERROR",
		4:  "ID_TYPE_POLICY",
		5:  "ID_TYPE_REQUEST",
		6:  "ID_TYPE_PROVIDER",
		7:  "ID_TYPE_CONNECTION",
		8:  "ID_TYPE_INVITE",
		9:  "ID_TYPE_POLICY_BUILDER",
		10: "ID_TYPE_POLICY_REPO",
	}
	IDType_value = map[string]int32{
		"ID_TYPE_UNKNOWN":        0,
		"ID_TYPE_ACCOUNT":        1,
		"ID_TYPE_TENANT":         2,
		"ID_TYPE_ERROR":          3,
		"ID_TYPE_POLICY":         4,
		"ID_TYPE_REQUEST":        5,
		"ID_TYPE_PROVIDER":       6,
		"ID_TYPE_CONNECTION":     7,
		"ID_TYPE_INVITE":         8,
		"ID_TYPE_POLICY_BUILDER": 9,
		"ID_TYPE_POLICY_REPO":    10,
	}
)

func (x IDType) Enum() *IDType {
	p := new(IDType)
	*p = x
	return p
}

func (x IDType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IDType) Descriptor() protoreflect.EnumDescriptor {
	return file_aserto_options_v1_ids_proto_enumTypes[0].Descriptor()
}

func (IDType) Type() protoreflect.EnumType {
	return &file_aserto_options_v1_ids_proto_enumTypes[0]
}

func (x IDType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IDType.Descriptor instead.
func (IDType) EnumDescriptor() ([]byte, []int) {
	return file_aserto_options_v1_ids_proto_rawDescGZIP(), []int{0}
}

var file_aserto_options_v1_ids_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*IDType)(nil),
		Field:         50002,
		Name:          "aserto.options.v1.id_type",
		Tag:           "varint,50002,opt,name=id_type,enum=aserto.options.v1.IDType",
		Filename:      "aserto/options/v1/ids.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50002,
		Name:          "aserto.options.v1.id",
		Tag:           "bytes,50002,opt,name=id",
		Filename:      "aserto/options/v1/ids.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional aserto.options.v1.IDType id_type = 50002;
	E_IdType = &file_aserto_options_v1_ids_proto_extTypes[0]
)

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// optional string id = 50002;
	E_Id = &file_aserto_options_v1_ids_proto_extTypes[1]
)

var File_aserto_options_v1_ids_proto protoreflect.FileDescriptor

const file_aserto_options_v1_ids_proto_rawDesc = "" +
	"\n" +
	"\x1baserto/options/v1/ids.proto\x12\x11aserto.options.v1\x1a google/protobuf/descriptor.proto*\xf9\x01\n" +
	"\x06IDType\x12\x13\n" +
	"\x0fID_TYPE_UNKNOWN\x10\x00\x12\x13\n" +
	"\x0fID_TYPE_ACCOUNT\x10\x01\x12\x12\n" +
	"\x0eID_TYPE_TENANT\x10\x02\x12\x11\n" +
	"\rID_TYPE_ERROR\x10\x03\x12\x12\n" +
	"\x0eID_TYPE_POLICY\x10\x04\x12\x13\n" +
	"\x0fID_TYPE_REQUEST\x10\x05\x12\x14\n" +
	"\x10ID_TYPE_PROVIDER\x10\x06\x12\x16\n" +
	"\x12ID_TYPE_CONNECTION\x10\a\x12\x12\n" +
	"\x0eID_TYPE_INVITE\x10\b\x12\x1a\n" +
	"\x16ID_TYPE_POLICY_BUILDER\x10\t\x12\x17\n" +
	"\x13ID_TYPE_POLICY_REPO\x10\n" +
	":V\n" +
	"\aid_type\x12\x1d.google.protobuf.FieldOptions\x18҆\x03 \x01(\x0e2\x19.aserto.options.v1.IDTypeR\x06idType\x88\x01\x01:6\n" +
	"\x02id\x12!.google.protobuf.EnumValueOptions\x18҆\x03 \x01(\tR\x02id\x88\x01\x01B9Z7github.com/aserto-dev/go-grpc/aserto/options/v1;optionsb\x06proto3"

var (
	file_aserto_options_v1_ids_proto_rawDescOnce sync.Once
	file_aserto_options_v1_ids_proto_rawDescData []byte
)

func file_aserto_options_v1_ids_proto_rawDescGZIP() []byte {
	file_aserto_options_v1_ids_proto_rawDescOnce.Do(func() {
		file_aserto_options_v1_ids_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aserto_options_v1_ids_proto_rawDesc), len(file_aserto_options_v1_ids_proto_rawDesc)))
	})
	return file_aserto_options_v1_ids_proto_rawDescData
}

var file_aserto_options_v1_ids_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_aserto_options_v1_ids_proto_goTypes = []any{
	(IDType)(0),                           // 0: aserto.options.v1.IDType
	(*descriptorpb.FieldOptions)(nil),     // 1: google.protobuf.FieldOptions
	(*descriptorpb.EnumValueOptions)(nil), // 2: google.protobuf.EnumValueOptions
}
var file_aserto_options_v1_ids_proto_depIdxs = []int32{
	1, // 0: aserto.options.v1.id_type:extendee -> google.protobuf.FieldOptions
	2, // 1: aserto.options.v1.id:extendee -> google.protobuf.EnumValueOptions
	0, // 2: aserto.options.v1.id_type:type_name -> aserto.options.v1.IDType
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	2, // [2:3] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_aserto_options_v1_ids_proto_init() }
func file_aserto_options_v1_ids_proto_init() {
	if File_aserto_options_v1_ids_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aserto_options_v1_ids_proto_rawDesc), len(file_aserto_options_v1_ids_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_aserto_options_v1_ids_proto_goTypes,
		DependencyIndexes: file_aserto_options_v1_ids_proto_depIdxs,
		EnumInfos:         file_aserto_options_v1_ids_proto_enumTypes,
		ExtensionInfos:    file_aserto_options_v1_ids_proto_extTypes,
	}.Build()
	File_aserto_options_v1_ids_proto = out.File
	file_aserto_options_v1_ids_proto_goTypes = nil
	file_aserto_options_v1_ids_proto_depIdxs = nil
}
