// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: aserto/api/v2/user.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserStatus int32

const (
	UserStatus_USER_STATUS_UNKNOWN     UserStatus = 0 // User status undefined
	UserStatus_USER_STATUS_STAGED      UserStatus = 1 // Staged status, is when the user object is first created, before the activation flow is initiated, or if there is a pending admin action.
	UserStatus_USER_STATUS_PROVISIONED UserStatus = 2 // Provisioned status, is when the user object is provisioned, but the user has not provided verification by clicking through the activation email or provided a password.
	UserStatus_USER_STATUS_ACTIVE      UserStatus = 3 // Active status, is when:
	// * An admin adds a user and sets the user password without requiring email verification.
	// * An admin adds a user, sets the user password, and requires the user to set their password when they first sign-in.
	// * A user self-registers into a custom app or IDP and email verification is not required.
	// * An admin explicitly activates the user.
	UserStatus_USER_STATUS_RECOVERY         UserStatus = 4 // Recovery status, when the user requests a password reset or an admin initiates one on their behalf.
	UserStatus_USER_STATUS_PASSWORD_EXPIRED UserStatus = 5 // Password expired, status when the users' password has expired and the account requires an update to the password before a user is granted access.
	UserStatus_USER_STATUS_LOCKED_OUT       UserStatus = 6 // Locked out status, is when the user exceeds the number of login attempts defined in the login policy.
	UserStatus_USER_STATUS_SUSPENDED        UserStatus = 7 // Suspended status, when an admin explicitly suspends the user account.
	UserStatus_USER_STATUS_DEPROVISIONED    UserStatus = 8 // Deprovisioned status, is when an administrator explicitly deactivates or deprovisions/deletes the account.
)

// Enum value maps for UserStatus.
var (
	UserStatus_name = map[int32]string{
		0: "USER_STATUS_UNKNOWN",
		1: "USER_STATUS_STAGED",
		2: "USER_STATUS_PROVISIONED",
		3: "USER_STATUS_ACTIVE",
		4: "USER_STATUS_RECOVERY",
		5: "USER_STATUS_PASSWORD_EXPIRED",
		6: "USER_STATUS_LOCKED_OUT",
		7: "USER_STATUS_SUSPENDED",
		8: "USER_STATUS_DEPROVISIONED",
	}
	UserStatus_value = map[string]int32{
		"USER_STATUS_UNKNOWN":          0,
		"USER_STATUS_STAGED":           1,
		"USER_STATUS_PROVISIONED":      2,
		"USER_STATUS_ACTIVE":           3,
		"USER_STATUS_RECOVERY":         4,
		"USER_STATUS_PASSWORD_EXPIRED": 5,
		"USER_STATUS_LOCKED_OUT":       6,
		"USER_STATUS_SUSPENDED":        7,
		"USER_STATUS_DEPROVISIONED":    8,
	}
)

func (x UserStatus) Enum() *UserStatus {
	p := new(UserStatus)
	*p = x
	return p
}

func (x UserStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_aserto_api_v2_user_proto_enumTypes[0].Descriptor()
}

func (UserStatus) Type() protoreflect.EnumType {
	return &file_aserto_api_v2_user_proto_enumTypes[0]
}

func (x UserStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserStatus.Descriptor instead.
func (UserStatus) EnumDescriptor() ([]byte, []int) {
	return file_aserto_api_v2_user_proto_rawDescGZIP(), []int{0}
}

type UserProperties struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`                                  // main email address of user
	Picture       string                 `protobuf:"bytes,2,opt,name=picture,proto3" json:"picture,omitempty"`                              // URL to user's picture
	Status        UserStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=aserto.api.v2.UserStatus" json:"status,omitempty"` // user lifecycle status
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProperties) Reset() {
	*x = UserProperties{}
	mi := &file_aserto_api_v2_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProperties) ProtoMessage() {}

func (x *UserProperties) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_api_v2_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProperties.ProtoReflect.Descriptor instead.
func (*UserProperties) Descriptor() ([]byte, []int) {
	return file_aserto_api_v2_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserProperties) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserProperties) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

func (x *UserProperties) GetStatus() UserStatus {
	if x != nil {
		return x.Status
	}
	return UserStatus_USER_STATUS_UNKNOWN
}

var File_aserto_api_v2_user_proto protoreflect.FileDescriptor

const file_aserto_api_v2_user_proto_rawDesc = "" +
	"\n" +
	"\x18aserto/api/v2/user.proto\x12\raserto.api.v2\"s\n" +
	"\x0eUserProperties\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x18\n" +
	"\apicture\x18\x02 \x01(\tR\apicture\x121\n" +
	"\x06status\x18\x03 \x01(\x0e2\x19.aserto.api.v2.UserStatusR\x06status*\x84\x02\n" +
	"\n" +
	"UserStatus\x12\x17\n" +
	"\x13USER_STATUS_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12USER_STATUS_STAGED\x10\x01\x12\x1b\n" +
	"\x17USER_STATUS_PROVISIONED\x10\x02\x12\x16\n" +
	"\x12USER_STATUS_ACTIVE\x10\x03\x12\x18\n" +
	"\x14USER_STATUS_RECOVERY\x10\x04\x12 \n" +
	"\x1cUSER_STATUS_PASSWORD_EXPIRED\x10\x05\x12\x1a\n" +
	"\x16USER_STATUS_LOCKED_OUT\x10\x06\x12\x19\n" +
	"\x15USER_STATUS_SUSPENDED\x10\a\x12\x1d\n" +
	"\x19USER_STATUS_DEPROVISIONED\x10\bBAZ/github.com/aserto-dev/go-grpc/aserto/api/v2;api\xaa\x02\rAserto.API.V2b\x06proto3"

var (
	file_aserto_api_v2_user_proto_rawDescOnce sync.Once
	file_aserto_api_v2_user_proto_rawDescData []byte
)

func file_aserto_api_v2_user_proto_rawDescGZIP() []byte {
	file_aserto_api_v2_user_proto_rawDescOnce.Do(func() {
		file_aserto_api_v2_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aserto_api_v2_user_proto_rawDesc), len(file_aserto_api_v2_user_proto_rawDesc)))
	})
	return file_aserto_api_v2_user_proto_rawDescData
}

var file_aserto_api_v2_user_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_aserto_api_v2_user_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_aserto_api_v2_user_proto_goTypes = []any{
	(UserStatus)(0),        // 0: aserto.api.v2.UserStatus
	(*UserProperties)(nil), // 1: aserto.api.v2.UserProperties
}
var file_aserto_api_v2_user_proto_depIdxs = []int32{
	0, // 0: aserto.api.v2.UserProperties.status:type_name -> aserto.api.v2.UserStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_aserto_api_v2_user_proto_init() }
func file_aserto_api_v2_user_proto_init() {
	if File_aserto_api_v2_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aserto_api_v2_user_proto_rawDesc), len(file_aserto_api_v2_user_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aserto_api_v2_user_proto_goTypes,
		DependencyIndexes: file_aserto_api_v2_user_proto_depIdxs,
		EnumInfos:         file_aserto_api_v2_user_proto_enumTypes,
		MessageInfos:      file_aserto_api_v2_user_proto_msgTypes,
	}.Build()
	File_aserto_api_v2_user_proto = out.File
	file_aserto_api_v2_user_proto_goTypes = nil
	file_aserto_api_v2_user_proto_depIdxs = nil
}
