// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: aserto/api/v2/workflows.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkflowState int32

const (
	WorkflowState_WORKFLOW_STATE_UNKNOWN WorkflowState = 0 // Value not set.
	WorkflowState_WORKFLOW_STATE_RUNNING WorkflowState = 1 // Workflow is running.
	WorkflowState_WORKFLOW_STATE_DONE    WorkflowState = 2 // Workflow has completed.
)

// Enum value maps for WorkflowState.
var (
	WorkflowState_name = map[int32]string{
		0: "WORKFLOW_STATE_UNKNOWN",
		1: "WORKFLOW_STATE_RUNNING",
		2: "WORKFLOW_STATE_DONE",
	}
	WorkflowState_value = map[string]int32{
		"WORKFLOW_STATE_UNKNOWN": 0,
		"WORKFLOW_STATE_RUNNING": 1,
		"WORKFLOW_STATE_DONE":    2,
	}
)

func (x WorkflowState) Enum() *WorkflowState {
	p := new(WorkflowState)
	*p = x
	return p
}

func (x WorkflowState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkflowState) Descriptor() protoreflect.EnumDescriptor {
	return file_aserto_api_v2_workflows_proto_enumTypes[0].Descriptor()
}

func (WorkflowState) Type() protoreflect.EnumType {
	return &file_aserto_api_v2_workflows_proto_enumTypes[0]
}

func (x WorkflowState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkflowState.Descriptor instead.
func (WorkflowState) EnumDescriptor() ([]byte, []int) {
	return file_aserto_api_v2_workflows_proto_rawDescGZIP(), []int{0}
}

type ActivityResponseState int32

const (
	ActivityResponseState_ACTIVITY_RESPONSE_STATE_UNKNOWN   ActivityResponseState = 0 // Value not set.
	ActivityResponseState_ACTIVITY_RESPONSE_STATE_CREATED   ActivityResponseState = 1 // Resouce managed by the activity was created.
	ActivityResponseState_ACTIVITY_RESPONSE_STATE_DELETED   ActivityResponseState = 2 // Resouce managed by the activity was deleted.
	ActivityResponseState_ACTIVITY_RESPONSE_STATE_UPDATED   ActivityResponseState = 3 // Resouce managed by the activity was updated.
	ActivityResponseState_ACTIVITY_RESPONSE_STATE_UNCHANGED ActivityResponseState = 4 // Resouce managed by the activity was unchanged.
)

// Enum value maps for ActivityResponseState.
var (
	ActivityResponseState_name = map[int32]string{
		0: "ACTIVITY_RESPONSE_STATE_UNKNOWN",
		1: "ACTIVITY_RESPONSE_STATE_CREATED",
		2: "ACTIVITY_RESPONSE_STATE_DELETED",
		3: "ACTIVITY_RESPONSE_STATE_UPDATED",
		4: "ACTIVITY_RESPONSE_STATE_UNCHANGED",
	}
	ActivityResponseState_value = map[string]int32{
		"ACTIVITY_RESPONSE_STATE_UNKNOWN":   0,
		"ACTIVITY_RESPONSE_STATE_CREATED":   1,
		"ACTIVITY_RESPONSE_STATE_DELETED":   2,
		"ACTIVITY_RESPONSE_STATE_UPDATED":   3,
		"ACTIVITY_RESPONSE_STATE_UNCHANGED": 4,
	}
)

func (x ActivityResponseState) Enum() *ActivityResponseState {
	p := new(ActivityResponseState)
	*p = x
	return p
}

func (x ActivityResponseState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActivityResponseState) Descriptor() protoreflect.EnumDescriptor {
	return file_aserto_api_v2_workflows_proto_enumTypes[1].Descriptor()
}

func (ActivityResponseState) Type() protoreflect.EnumType {
	return &file_aserto_api_v2_workflows_proto_enumTypes[1]
}

func (x ActivityResponseState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActivityResponseState.Descriptor instead.
func (ActivityResponseState) EnumDescriptor() ([]byte, []int) {
	return file_aserto_api_v2_workflows_proto_rawDescGZIP(), []int{1}
}

type WorkflowRunType int32

const (
	WorkflowRunType_WORKFLOW_RUN_TYPE_UNKNOWN WorkflowRunType = 0 // Value not set.
	WorkflowRunType_WORKFLOW_RUN_TYPE_NOOP    WorkflowRunType = 1 // Workflow run is a no-op.
	WorkflowRunType_WORKFLOW_RUN_TYPE_EXECUTE WorkflowRunType = 2 // Workflow run is set to execute.
)

// Enum value maps for WorkflowRunType.
var (
	WorkflowRunType_name = map[int32]string{
		0: "WORKFLOW_RUN_TYPE_UNKNOWN",
		1: "WORKFLOW_RUN_TYPE_NOOP",
		2: "WORKFLOW_RUN_TYPE_EXECUTE",
	}
	WorkflowRunType_value = map[string]int32{
		"WORKFLOW_RUN_TYPE_UNKNOWN": 0,
		"WORKFLOW_RUN_TYPE_NOOP":    1,
		"WORKFLOW_RUN_TYPE_EXECUTE": 2,
	}
)

func (x WorkflowRunType) Enum() *WorkflowRunType {
	p := new(WorkflowRunType)
	*p = x
	return p
}

func (x WorkflowRunType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkflowRunType) Descriptor() protoreflect.EnumDescriptor {
	return file_aserto_api_v2_workflows_proto_enumTypes[2].Descriptor()
}

func (WorkflowRunType) Type() protoreflect.EnumType {
	return &file_aserto_api_v2_workflows_proto_enumTypes[2]
}

func (x WorkflowRunType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkflowRunType.Descriptor instead.
func (WorkflowRunType) EnumDescriptor() ([]byte, []int) {
	return file_aserto_api_v2_workflows_proto_rawDescGZIP(), []int{2}
}

type WorkflowEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	WorkflowName  string                 `protobuf:"bytes,3,opt,name=workflow_name,json=workflowName,proto3" json:"workflow_name,omitempty"`
	Status        WorkflowState          `protobuf:"varint,4,opt,name=status,proto3,enum=aserto.api.v2.WorkflowState" json:"status,omitempty"`
	Event         *structpb.Struct       `protobuf:"bytes,5,opt,name=event,proto3" json:"event,omitempty"`
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowEvent) Reset() {
	*x = WorkflowEvent{}
	mi := &file_aserto_api_v2_workflows_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowEvent) ProtoMessage() {}

func (x *WorkflowEvent) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_api_v2_workflows_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowEvent.ProtoReflect.Descriptor instead.
func (*WorkflowEvent) Descriptor() ([]byte, []int) {
	return file_aserto_api_v2_workflows_proto_rawDescGZIP(), []int{0}
}

func (x *WorkflowEvent) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *WorkflowEvent) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *WorkflowEvent) GetWorkflowName() string {
	if x != nil {
		return x.WorkflowName
	}
	return ""
}

func (x *WorkflowEvent) GetStatus() WorkflowState {
	if x != nil {
		return x.Status
	}
	return WorkflowState_WORKFLOW_STATE_UNKNOWN
}

func (x *WorkflowEvent) GetEvent() *structpb.Struct {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *WorkflowEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ActivityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Activity      string                 `protobuf:"bytes,1,opt,name=activity,proto3" json:"activity,omitempty"`
	State         ActivityResponseState  `protobuf:"varint,2,opt,name=state,proto3,enum=aserto.api.v2.ActivityResponseState" json:"state,omitempty"`
	Response      *structpb.Value        `protobuf:"bytes,3,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityResponse) Reset() {
	*x = ActivityResponse{}
	mi := &file_aserto_api_v2_workflows_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityResponse) ProtoMessage() {}

func (x *ActivityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_api_v2_workflows_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityResponse.ProtoReflect.Descriptor instead.
func (*ActivityResponse) Descriptor() ([]byte, []int) {
	return file_aserto_api_v2_workflows_proto_rawDescGZIP(), []int{1}
}

func (x *ActivityResponse) GetActivity() string {
	if x != nil {
		return x.Activity
	}
	return ""
}

func (x *ActivityResponse) GetState() ActivityResponseState {
	if x != nil {
		return x.State
	}
	return ActivityResponseState_ACTIVITY_RESPONSE_STATE_UNKNOWN
}

func (x *ActivityResponse) GetResponse() *structpb.Value {
	if x != nil {
		return x.Response
	}
	return nil
}

type WorkflowOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunType       WorkflowRunType        `protobuf:"varint,1,opt,name=run_type,json=runType,proto3,enum=aserto.api.v2.WorkflowRunType" json:"run_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowOptions) Reset() {
	*x = WorkflowOptions{}
	mi := &file_aserto_api_v2_workflows_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowOptions) ProtoMessage() {}

func (x *WorkflowOptions) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_api_v2_workflows_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowOptions.ProtoReflect.Descriptor instead.
func (*WorkflowOptions) Descriptor() ([]byte, []int) {
	return file_aserto_api_v2_workflows_proto_rawDescGZIP(), []int{2}
}

func (x *WorkflowOptions) GetRunType() WorkflowRunType {
	if x != nil {
		return x.RunType
	}
	return WorkflowRunType_WORKFLOW_RUN_TYPE_UNKNOWN
}

type WorkflowResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Workflow          string                 `protobuf:"bytes,1,opt,name=workflow,proto3" json:"workflow,omitempty"`
	Options           *WorkflowOptions       `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	ActivityResult    []*ActivityResponse    `protobuf:"bytes,3,rep,name=activity_result,json=activityResult,proto3" json:"activity_result,omitempty"`
	WorkflowResponses []*WorkflowResponse    `protobuf:"bytes,4,rep,name=workflow_responses,json=workflowResponses,proto3" json:"workflow_responses,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WorkflowResponse) Reset() {
	*x = WorkflowResponse{}
	mi := &file_aserto_api_v2_workflows_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowResponse) ProtoMessage() {}

func (x *WorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_api_v2_workflows_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowResponse.ProtoReflect.Descriptor instead.
func (*WorkflowResponse) Descriptor() ([]byte, []int) {
	return file_aserto_api_v2_workflows_proto_rawDescGZIP(), []int{3}
}

func (x *WorkflowResponse) GetWorkflow() string {
	if x != nil {
		return x.Workflow
	}
	return ""
}

func (x *WorkflowResponse) GetOptions() *WorkflowOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *WorkflowResponse) GetActivityResult() []*ActivityResponse {
	if x != nil {
		return x.ActivityResult
	}
	return nil
}

func (x *WorkflowResponse) GetWorkflowResponses() []*WorkflowResponse {
	if x != nil {
		return x.WorkflowResponses
	}
	return nil
}

var File_aserto_api_v2_workflows_proto protoreflect.FileDescriptor

const file_aserto_api_v2_workflows_proto_rawDesc = "" +
	"\n" +
	"\x1daserto/api/v2/workflows.proto\x12\raserto.api.v2\x1a\x1cgoogle/protobuf/struct.proto\"\xeb\x01\n" +
	"\rWorkflowEvent\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12#\n" +
	"\rworkflow_name\x18\x03 \x01(\tR\fworkflowName\x124\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1c.aserto.api.v2.WorkflowStateR\x06status\x12-\n" +
	"\x05event\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x05event\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\"\x9e\x01\n" +
	"\x10ActivityResponse\x12\x1a\n" +
	"\bactivity\x18\x01 \x01(\tR\bactivity\x12:\n" +
	"\x05state\x18\x02 \x01(\x0e2$.aserto.api.v2.ActivityResponseStateR\x05state\x122\n" +
	"\bresponse\x18\x03 \x01(\v2\x16.google.protobuf.ValueR\bresponse\"L\n" +
	"\x0fWorkflowOptions\x129\n" +
	"\brun_type\x18\x01 \x01(\x0e2\x1e.aserto.api.v2.WorkflowRunTypeR\arunType\"\x82\x02\n" +
	"\x10WorkflowResponse\x12\x1a\n" +
	"\bworkflow\x18\x01 \x01(\tR\bworkflow\x128\n" +
	"\aoptions\x18\x02 \x01(\v2\x1e.aserto.api.v2.WorkflowOptionsR\aoptions\x12H\n" +
	"\x0factivity_result\x18\x03 \x03(\v2\x1f.aserto.api.v2.ActivityResponseR\x0eactivityResult\x12N\n" +
	"\x12workflow_responses\x18\x04 \x03(\v2\x1f.aserto.api.v2.WorkflowResponseR\x11workflowResponses*`\n" +
	"\rWorkflowState\x12\x1a\n" +
	"\x16WORKFLOW_STATE_UNKNOWN\x10\x00\x12\x1a\n" +
	"\x16WORKFLOW_STATE_RUNNING\x10\x01\x12\x17\n" +
	"\x13WORKFLOW_STATE_DONE\x10\x02*\xd2\x01\n" +
	"\x15ActivityResponseState\x12#\n" +
	"\x1fACTIVITY_RESPONSE_STATE_UNKNOWN\x10\x00\x12#\n" +
	"\x1fACTIVITY_RESPONSE_STATE_CREATED\x10\x01\x12#\n" +
	"\x1fACTIVITY_RESPONSE_STATE_DELETED\x10\x02\x12#\n" +
	"\x1fACTIVITY_RESPONSE_STATE_UPDATED\x10\x03\x12%\n" +
	"!ACTIVITY_RESPONSE_STATE_UNCHANGED\x10\x04*k\n" +
	"\x0fWorkflowRunType\x12\x1d\n" +
	"\x19WORKFLOW_RUN_TYPE_UNKNOWN\x10\x00\x12\x1a\n" +
	"\x16WORKFLOW_RUN_TYPE_NOOP\x10\x01\x12\x1d\n" +
	"\x19WORKFLOW_RUN_TYPE_EXECUTE\x10\x02BAZ/github.com/aserto-dev/go-grpc/aserto/api/v2;api\xaa\x02\rAserto.API.V2b\x06proto3"

var (
	file_aserto_api_v2_workflows_proto_rawDescOnce sync.Once
	file_aserto_api_v2_workflows_proto_rawDescData []byte
)

func file_aserto_api_v2_workflows_proto_rawDescGZIP() []byte {
	file_aserto_api_v2_workflows_proto_rawDescOnce.Do(func() {
		file_aserto_api_v2_workflows_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aserto_api_v2_workflows_proto_rawDesc), len(file_aserto_api_v2_workflows_proto_rawDesc)))
	})
	return file_aserto_api_v2_workflows_proto_rawDescData
}

var file_aserto_api_v2_workflows_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_aserto_api_v2_workflows_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_aserto_api_v2_workflows_proto_goTypes = []any{
	(WorkflowState)(0),         // 0: aserto.api.v2.WorkflowState
	(ActivityResponseState)(0), // 1: aserto.api.v2.ActivityResponseState
	(WorkflowRunType)(0),       // 2: aserto.api.v2.WorkflowRunType
	(*WorkflowEvent)(nil),      // 3: aserto.api.v2.WorkflowEvent
	(*ActivityResponse)(nil),   // 4: aserto.api.v2.ActivityResponse
	(*WorkflowOptions)(nil),    // 5: aserto.api.v2.WorkflowOptions
	(*WorkflowResponse)(nil),   // 6: aserto.api.v2.WorkflowResponse
	(*structpb.Struct)(nil),    // 7: google.protobuf.Struct
	(*structpb.Value)(nil),     // 8: google.protobuf.Value
}
var file_aserto_api_v2_workflows_proto_depIdxs = []int32{
	0, // 0: aserto.api.v2.WorkflowEvent.status:type_name -> aserto.api.v2.WorkflowState
	7, // 1: aserto.api.v2.WorkflowEvent.event:type_name -> google.protobuf.Struct
	1, // 2: aserto.api.v2.ActivityResponse.state:type_name -> aserto.api.v2.ActivityResponseState
	8, // 3: aserto.api.v2.ActivityResponse.response:type_name -> google.protobuf.Value
	2, // 4: aserto.api.v2.WorkflowOptions.run_type:type_name -> aserto.api.v2.WorkflowRunType
	5, // 5: aserto.api.v2.WorkflowResponse.options:type_name -> aserto.api.v2.WorkflowOptions
	4, // 6: aserto.api.v2.WorkflowResponse.activity_result:type_name -> aserto.api.v2.ActivityResponse
	6, // 7: aserto.api.v2.WorkflowResponse.workflow_responses:type_name -> aserto.api.v2.WorkflowResponse
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_aserto_api_v2_workflows_proto_init() }
func file_aserto_api_v2_workflows_proto_init() {
	if File_aserto_api_v2_workflows_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aserto_api_v2_workflows_proto_rawDesc), len(file_aserto_api_v2_workflows_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aserto_api_v2_workflows_proto_goTypes,
		DependencyIndexes: file_aserto_api_v2_workflows_proto_depIdxs,
		EnumInfos:         file_aserto_api_v2_workflows_proto_enumTypes,
		MessageInfos:      file_aserto_api_v2_workflows_proto_msgTypes,
	}.Build()
	File_aserto_api_v2_workflows_proto = out.File
	file_aserto_api_v2_workflows_proto_goTypes = nil
	file_aserto_api_v2_workflows_proto_depIdxs = nil
}
