// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: aserto/tenant/profile/v1/profile.proto

package profile

import (
	v1 "github.com/aserto-dev/go-grpc/aserto/api/v1"
	_ "github.com/aserto-dev/go-grpc/aserto/options/v1"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_aserto_tenant_profile_v1_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_tenant_profile_v1_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_aserto_tenant_profile_v1_profile_proto_rawDescGZIP(), []int{0}
}

type GetProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        *v1.Tenant             `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileResponse) Reset() {
	*x = GetProfileResponse{}
	mi := &file_aserto_tenant_profile_v1_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileResponse) ProtoMessage() {}

func (x *GetProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_tenant_profile_v1_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileResponse.ProtoReflect.Descriptor instead.
func (*GetProfileResponse) Descriptor() ([]byte, []int) {
	return file_aserto_tenant_profile_v1_profile_proto_rawDescGZIP(), []int{1}
}

func (x *GetProfileResponse) GetTenant() *v1.Tenant {
	if x != nil {
		return x.Tenant
	}
	return nil
}

type GetInvitesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInvitesRequest) Reset() {
	*x = GetInvitesRequest{}
	mi := &file_aserto_tenant_profile_v1_profile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInvitesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvitesRequest) ProtoMessage() {}

func (x *GetInvitesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_tenant_profile_v1_profile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInvitesRequest.ProtoReflect.Descriptor instead.
func (*GetInvitesRequest) Descriptor() ([]byte, []int) {
	return file_aserto_tenant_profile_v1_profile_proto_rawDescGZIP(), []int{2}
}

type GetInvitesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invites       []*v1.Invite           `protobuf:"bytes,1,rep,name=invites,proto3" json:"invites,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInvitesResponse) Reset() {
	*x = GetInvitesResponse{}
	mi := &file_aserto_tenant_profile_v1_profile_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInvitesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvitesResponse) ProtoMessage() {}

func (x *GetInvitesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_tenant_profile_v1_profile_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInvitesResponse.ProtoReflect.Descriptor instead.
func (*GetInvitesResponse) Descriptor() ([]byte, []int) {
	return file_aserto_tenant_profile_v1_profile_proto_rawDescGZIP(), []int{3}
}

func (x *GetInvitesResponse) GetInvites() []*v1.Invite {
	if x != nil {
		return x.Invites
	}
	return nil
}

type InviteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"` // email from auth0
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`   // role assigned to the user on accept
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteUserRequest) Reset() {
	*x = InviteUserRequest{}
	mi := &file_aserto_tenant_profile_v1_profile_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteUserRequest) ProtoMessage() {}

func (x *InviteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_tenant_profile_v1_profile_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteUserRequest.ProtoReflect.Descriptor instead.
func (*InviteUserRequest) Descriptor() ([]byte, []int) {
	return file_aserto_tenant_profile_v1_profile_proto_rawDescGZIP(), []int{4}
}

func (x *InviteUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *InviteUserRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type InviteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteUserResponse) Reset() {
	*x = InviteUserResponse{}
	mi := &file_aserto_tenant_profile_v1_profile_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteUserResponse) ProtoMessage() {}

func (x *InviteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_tenant_profile_v1_profile_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteUserResponse.ProtoReflect.Descriptor instead.
func (*InviteUserResponse) Descriptor() ([]byte, []int) {
	return file_aserto_tenant_profile_v1_profile_proto_rawDescGZIP(), []int{5}
}

func (x *InviteUserResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RespondToInviteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        v1.InviteStatus        `protobuf:"varint,2,opt,name=status,proto3,enum=aserto.api.v1.InviteStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespondToInviteRequest) Reset() {
	*x = RespondToInviteRequest{}
	mi := &file_aserto_tenant_profile_v1_profile_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespondToInviteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespondToInviteRequest) ProtoMessage() {}

func (x *RespondToInviteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_tenant_profile_v1_profile_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespondToInviteRequest.ProtoReflect.Descriptor instead.
func (*RespondToInviteRequest) Descriptor() ([]byte, []int) {
	return file_aserto_tenant_profile_v1_profile_proto_rawDescGZIP(), []int{6}
}

func (x *RespondToInviteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RespondToInviteRequest) GetStatus() v1.InviteStatus {
	if x != nil {
		return x.Status
	}
	return v1.InviteStatus(0)
}

type RespondToInviteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespondToInviteResponse) Reset() {
	*x = RespondToInviteResponse{}
	mi := &file_aserto_tenant_profile_v1_profile_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespondToInviteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespondToInviteResponse) ProtoMessage() {}

func (x *RespondToInviteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_tenant_profile_v1_profile_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespondToInviteResponse.ProtoReflect.Descriptor instead.
func (*RespondToInviteResponse) Descriptor() ([]byte, []int) {
	return file_aserto_tenant_profile_v1_profile_proto_rawDescGZIP(), []int{7}
}

type RemoveMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMemberRequest) Reset() {
	*x = RemoveMemberRequest{}
	mi := &file_aserto_tenant_profile_v1_profile_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMemberRequest) ProtoMessage() {}

func (x *RemoveMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_tenant_profile_v1_profile_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMemberRequest.ProtoReflect.Descriptor instead.
func (*RemoveMemberRequest) Descriptor() ([]byte, []int) {
	return file_aserto_tenant_profile_v1_profile_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveMemberRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type RemoveMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMemberResponse) Reset() {
	*x = RemoveMemberResponse{}
	mi := &file_aserto_tenant_profile_v1_profile_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMemberResponse) ProtoMessage() {}

func (x *RemoveMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_tenant_profile_v1_profile_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMemberResponse.ProtoReflect.Descriptor instead.
func (*RemoveMemberResponse) Descriptor() ([]byte, []int) {
	return file_aserto_tenant_profile_v1_profile_proto_rawDescGZIP(), []int{9}
}

var File_aserto_tenant_profile_v1_profile_proto protoreflect.FileDescriptor

const file_aserto_tenant_profile_v1_profile_proto_rawDesc = "" +
	"\n" +
	"&aserto/tenant/profile/v1/profile.proto\x12\x18aserto.tenant.profile.v1\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x1baserto/options/v1/ids.proto\x1a\x1aaserto/api/v1/invite.proto\x1a\x1aaserto/api/v1/tenant.proto\"\x13\n" +
	"\x11GetProfileRequest\"C\n" +
	"\x12GetProfileResponse\x12-\n" +
	"\x06tenant\x18\x01 \x01(\v2\x15.aserto.api.v1.TenantR\x06tenant\"\x13\n" +
	"\x11GetInvitesRequest\"E\n" +
	"\x12GetInvitesResponse\x12/\n" +
	"\ainvites\x18\x01 \x03(\v2\x15.aserto.api.v1.InviteR\ainvites\"=\n" +
	"\x11InviteUserRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\"*\n" +
	"\x12InviteUserResponse\x12\x14\n" +
	"\x02id\x18\x01 \x01(\tB\x04\x90\xb5\x18\x01R\x02id\"c\n" +
	"\x16RespondToInviteRequest\x12\x14\n" +
	"\x02id\x18\x01 \x01(\tB\x04\x90\xb5\x18\bR\x02id\x123\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1b.aserto.api.v1.InviteStatusR\x06status\"\x19\n" +
	"\x17RespondToInviteResponse\":\n" +
	"\x13RemoveMemberRequest\x12#\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tB\x04\x90\xb5\x18\x01R\taccountId\"\x16\n" +
	"\x14RemoveMemberResponse2\xbc\n" +
	"\n" +
	"\aProfile\x12\xf3\x01\n" +
	"\n" +
	"GetProfile\x12+.aserto.tenant.profile.v1.GetProfileRequest\x1a,.aserto.tenant.profile.v1.GetProfileResponse\"\x89\x01\x92Ah\n" +
	"\aprofile\x12\x12Get tenant profile\x1a\x1bReturns the tenant profile.*\x13profile.get_profileb\x17\n" +
	"\a\n" +
	"\x03JWT\x12\x00\n" +
	"\f\n" +
	"\bTenantID\x12\x00\x82\xd3\xe4\x93\x02\x18\x12\x16/api/v1/tenant/profile\x12\x8b\x02\n" +
	"\n" +
	"GetInvites\x12+.aserto.tenant.profile.v1.GetInvitesRequest\x1a,.aserto.tenant.profile.v1.GetInvitesResponse\"\xa1\x01\x92Ax\n" +
	"\aprofile\x12\vGet invites\x1a2Returns collection of invitation for given tenant.*\x13profile.get_invitesb\x17\n" +
	"\a\n" +
	"\x03JWT\x12\x00\n" +
	"\f\n" +
	"\bTenantID\x12\x00\x82\xd3\xe4\x93\x02 \x12\x1e/api/v1/tenant/profile/invites\x12\xfc\x01\n" +
	"\n" +
	"InviteUser\x12+.aserto.tenant.profile.v1.InviteUserRequest\x1a,.aserto.tenant.profile.v1.InviteUserResponse\"\x92\x01\x92Af\n" +
	"\aprofile\x12\x15Invite user to tenant\x1a\x16Invite user to tenant.*\x13profile.invite_userb\x17\n" +
	"\a\n" +
	"\x03JWT\x12\x00\n" +
	"\f\n" +
	"\bTenantID\x12\x00\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/api/v1/tenant/profile/invites\x12\xa0\x02\n" +
	"\x0fRespondToInvite\x120.aserto.tenant.profile.v1.RespondToInviteRequest\x1a1.aserto.tenant.profile.v1.RespondToInviteResponse\"\xa7\x01\x92Av\n" +
	"\aprofile\x12\x18Respond to tenant invite\x1a\x1dRespond to tenant invitation.*\x19profile.respond_to_inviteb\x17\n" +
	"\a\n" +
	"\x03JWT\x12\x00\n" +
	"\f\n" +
	"\bTenantID\x12\x00\x82\xd3\xe4\x93\x02(:\x01*\"#/api/v1/tenant/profile/invites/{id}\x12\x8a\x02\n" +
	"\fRemoveMember\x12-.aserto.tenant.profile.v1.RemoveMemberRequest\x1a..aserto.tenant.profile.v1.RemoveMemberResponse\"\x9a\x01\x92Ad\n" +
	"\aprofile\x12\rRemove member\x1a\x1aRemove member from tenant.*\x15profile.remove_memberb\x17\n" +
	"\a\n" +
	"\x03JWT\x12\x00\n" +
	"\f\n" +
	"\bTenantID\x12\x00\x82\xd3\xe4\x93\x02-*+/api/v1/tenant/profile/members/{account_id}B\xc6\x01\x92A\x82\x01*\x01\x022\x10application/json:\x10application/jsonZ@\n" +
	"\x1a\n" +
	"\x03JWT\x12\x13\b\x02\x1a\rauthorization \x02\n" +
	"\"\n" +
	"\bTenantID\x12\x16\b\x02\x1a\x10aserto-tenant-id \x02b\x17\n" +
	"\a\n" +
	"\x03JWT\x12\x00\n" +
	"\f\n" +
	"\bTenantID\x12\x00Z>github.com/aserto-dev/go-grpc/aserto/tenant/profile/v1;profileb\x06proto3"

var (
	file_aserto_tenant_profile_v1_profile_proto_rawDescOnce sync.Once
	file_aserto_tenant_profile_v1_profile_proto_rawDescData []byte
)

func file_aserto_tenant_profile_v1_profile_proto_rawDescGZIP() []byte {
	file_aserto_tenant_profile_v1_profile_proto_rawDescOnce.Do(func() {
		file_aserto_tenant_profile_v1_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aserto_tenant_profile_v1_profile_proto_rawDesc), len(file_aserto_tenant_profile_v1_profile_proto_rawDesc)))
	})
	return file_aserto_tenant_profile_v1_profile_proto_rawDescData
}

var file_aserto_tenant_profile_v1_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_aserto_tenant_profile_v1_profile_proto_goTypes = []any{
	(*GetProfileRequest)(nil),       // 0: aserto.tenant.profile.v1.GetProfileRequest
	(*GetProfileResponse)(nil),      // 1: aserto.tenant.profile.v1.GetProfileResponse
	(*GetInvitesRequest)(nil),       // 2: aserto.tenant.profile.v1.GetInvitesRequest
	(*GetInvitesResponse)(nil),      // 3: aserto.tenant.profile.v1.GetInvitesResponse
	(*InviteUserRequest)(nil),       // 4: aserto.tenant.profile.v1.InviteUserRequest
	(*InviteUserResponse)(nil),      // 5: aserto.tenant.profile.v1.InviteUserResponse
	(*RespondToInviteRequest)(nil),  // 6: aserto.tenant.profile.v1.RespondToInviteRequest
	(*RespondToInviteResponse)(nil), // 7: aserto.tenant.profile.v1.RespondToInviteResponse
	(*RemoveMemberRequest)(nil),     // 8: aserto.tenant.profile.v1.RemoveMemberRequest
	(*RemoveMemberResponse)(nil),    // 9: aserto.tenant.profile.v1.RemoveMemberResponse
	(*v1.Tenant)(nil),               // 10: aserto.api.v1.Tenant
	(*v1.Invite)(nil),               // 11: aserto.api.v1.Invite
	(v1.InviteStatus)(0),            // 12: aserto.api.v1.InviteStatus
}
var file_aserto_tenant_profile_v1_profile_proto_depIdxs = []int32{
	10, // 0: aserto.tenant.profile.v1.GetProfileResponse.tenant:type_name -> aserto.api.v1.Tenant
	11, // 1: aserto.tenant.profile.v1.GetInvitesResponse.invites:type_name -> aserto.api.v1.Invite
	12, // 2: aserto.tenant.profile.v1.RespondToInviteRequest.status:type_name -> aserto.api.v1.InviteStatus
	0,  // 3: aserto.tenant.profile.v1.Profile.GetProfile:input_type -> aserto.tenant.profile.v1.GetProfileRequest
	2,  // 4: aserto.tenant.profile.v1.Profile.GetInvites:input_type -> aserto.tenant.profile.v1.GetInvitesRequest
	4,  // 5: aserto.tenant.profile.v1.Profile.InviteUser:input_type -> aserto.tenant.profile.v1.InviteUserRequest
	6,  // 6: aserto.tenant.profile.v1.Profile.RespondToInvite:input_type -> aserto.tenant.profile.v1.RespondToInviteRequest
	8,  // 7: aserto.tenant.profile.v1.Profile.RemoveMember:input_type -> aserto.tenant.profile.v1.RemoveMemberRequest
	1,  // 8: aserto.tenant.profile.v1.Profile.GetProfile:output_type -> aserto.tenant.profile.v1.GetProfileResponse
	3,  // 9: aserto.tenant.profile.v1.Profile.GetInvites:output_type -> aserto.tenant.profile.v1.GetInvitesResponse
	5,  // 10: aserto.tenant.profile.v1.Profile.InviteUser:output_type -> aserto.tenant.profile.v1.InviteUserResponse
	7,  // 11: aserto.tenant.profile.v1.Profile.RespondToInvite:output_type -> aserto.tenant.profile.v1.RespondToInviteResponse
	9,  // 12: aserto.tenant.profile.v1.Profile.RemoveMember:output_type -> aserto.tenant.profile.v1.RemoveMemberResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_aserto_tenant_profile_v1_profile_proto_init() }
func file_aserto_tenant_profile_v1_profile_proto_init() {
	if File_aserto_tenant_profile_v1_profile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aserto_tenant_profile_v1_profile_proto_rawDesc), len(file_aserto_tenant_profile_v1_profile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aserto_tenant_profile_v1_profile_proto_goTypes,
		DependencyIndexes: file_aserto_tenant_profile_v1_profile_proto_depIdxs,
		MessageInfos:      file_aserto_tenant_profile_v1_profile_proto_msgTypes,
	}.Build()
	File_aserto_tenant_profile_v1_profile_proto = out.File
	file_aserto_tenant_profile_v1_profile_proto_goTypes = nil
	file_aserto_tenant_profile_v1_profile_proto_depIdxs = nil
}
